@startuml
skinparam componentStyle rectangle
skinparam shadowing false
skinparam defaultTextAlignment left

cloud "Internet" as Internet
node "ISP CPE / ONT" as ISP
node "NGFW Cluster HA\nNAT / ACL / IPS\nRA VPN / S2S VPN" as FW
node "DMZ On-Site\nVLAN 130" as DMZ
node "Collapsed Core Pair\nCampus aggregation" as CORE

node "Access SW Users" as ASW1
node "Access SW Office" as ASW2
node "Access SW Wireless" as ASW3
node "Server / BigData Aggregation\n10/25 GbE recommended" as SVA

node "Business App Servers\nVLAN 50" as APP
node "DBMS / SAP Backend\nVLAN 60" as DB
node "Reserved Document Server\nMgmt only\nVLAN 70" as DOC
database "MongoDB Document Store\nRBAC\nVLAN 80" as MDB
node "Management Network\nVLAN 110" as MGMT
node "NMS / SIEM / IDS Collector\nVLAN 120" as SEC
node "Big Data Cluster\n10 nodes\nVLAN 90/91/100" as BD

node "Reverse Proxy / WAF" as WAF
node "Public Web Server" as WEB
node "REST/SOAP Public Facade" as API

node "PTP Radio A" as PTA
node "PTP Radio B" as PTB
node "Secondary Office Switch" as BR2
node "Secondary Users\nVLAN 150" as BUSER
node "Secondary Guest\nVLAN 160" as BGUEST
node "Secondary Mgmt\nVLAN 170" as BMGMT

node "Remote Main Site\nAnother Continent" as RHQ
actor "Managers Remote Users" as MGR

Internet -- ISP
ISP -- FW

FW -- DMZ
FW -- CORE
FW -- RHQ
FW -- MGR

DMZ -- WAF
DMZ -- WEB
DMZ -- API

CORE -- ASW1
CORE -- ASW2
CORE -- ASW3
CORE -- SVA

SVA -- APP
SVA -- DB
SVA -- DOC
SVA -- MDB
SVA -- MGMT
SVA -- SEC
SVA -- BD

CORE -- PTA
PTA -- PTB
PTB -- BR2
BR2 -- BUSER
BR2 -- BGUEST
BR2 -- BMGMT

note right of FW
Main security enforcement point:
- Internet/DMZ
- DMZ/Internal
- Remote Access VPN
- Site-to-Site VPN
end note

note right of MGMT
Separate management network:
switches, APs, firewalls,
hypervisors, iDRAC/iLO/IPMI,
security sensors
end note

note right of BD
Distributed processing and
high east-west traffic.
Separate data and mgmt planes.
end note
@enduml